#!/usr/bin/env bash
# Prepare the patched `ruffle_core` the bridge builds against.
#
# The one thing the Skua bridge needs from ruffle that the published crate does
# NOT expose is a host-callable "load a secondary SWF into the running game's
# ApplicationDomain" entry point — `Player::inject_swf_same_domain` (the AVM2
# loader types it needs live in private modules). Rather than vendor ruffle's
# whole ~200 MB source tree, we keep a tiny patch (`ruffle-skua-inject.patch`,
# one method) and apply it to a shallow checkout at the pinned rev here. The
# bridge's `[patch]` in Cargo.toml points at `.ruffle-fork/` (git-ignored).
#
# Idempotent: safe to re-run. Requires git + network to github.com.
set -euo pipefail

REV=f47766fdb17c46ad720f2c9861f62a17ab17b33c
HERE="$(cd "$(dirname "$0")" && pwd)"
DIR="$HERE/.ruffle-fork"
PATCH="$HERE/ruffle-skua-inject.patch"

if [ ! -d "$DIR/.git" ]; then
  echo "Cloning ruffle into $DIR ..."
  git clone --filter=blob:none https://github.com/ruffle-rs/ruffle "$DIR"
fi

cd "$DIR"
git fetch --depth 1 origin "$REV" 2>/dev/null || git fetch origin
# Reset any prior patch application, then pin + re-apply cleanly.
git checkout -f "$REV"
git apply "$PATCH"

# Append the [patch] block to the bridge's Cargo.toml so cargo redirects the
# ruffle_core git dependency to this fork. NOT committed to Cargo.toml: an
# always-present patch pointing at `.ruffle-fork/` (which exists only after this
# script runs) would break the default/offline `cargo build`. Idempotent.
CARGO="$HERE/skua-flash-bridge/Cargo.toml"
MARKER="# >>> skua ruffle fork patch (generated by prepare-ruffle-fork.sh)"
if ! grep -qF "$MARKER" "$CARGO"; then
  {
    echo ""
    echo "$MARKER"
    echo '[patch."https://github.com/ruffle-rs/ruffle"]'
    for pair in \
      "asc:tools/asc" "build_playerglobal:core/build_playerglobal" "flv-rs:flv" \
      "naga-agal:render/naga-agal" "naga-pixelbender:render/naga-pixelbender" \
      "pixel_bender:render/pixel_bender" "ruffle_common:core/common" \
      "ruffle_core:core" "ruffle_macros:core/macros" "ruffle_render:render" \
      "ruffle_render_wgpu:render/wgpu" "ruffle_video:video" "ruffle_wstr:wstr" \
      "swf:swf"; do
      name="${pair%%:*}"; rel="${pair##*:}"
      echo "$name = { path = \"../.ruffle-fork/$rel\" }"
    done
  } >> "$CARGO"
  echo "appended [patch] block to $CARGO"
fi

echo "ruffle fork ready at $DIR (rev $REV + skua inject patch)"
